spring.application.name=boletim-online

spring.datasource.url=jdbc:mysql://localhost:3306/boletim_online
spring.datasource.username=root
spring.datasource.password=Crashm08

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080